version: "3"
services:
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: bimanager
      POSTGRES_USER: superadministrador
      POSTGRES_PASSWORD: superadmin@123
    ports:
      - "5432:5432"

  postgres_test:
    image: postgres:latest
    environment:
      POSTGRES_DB: bimanager_test
      POSTGRES_USER: test
      POSTGRES_PASSWORD: test@123
    ports:
      - "5433:5432"
